version: "3.7"
services:
  backend:
    container_name: nelson-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 83:3000
    restart: always
    command: >
      sh -c "npx sequelize-cli db:migrate && 
             node app"
    networks:
      - nelson-network
networks:
  nelson-network:
    driver: bridge